In [1]:
import pandas as pd 
import numpy as np

In [2]:
df=  pd.read_csv("adult.csv")
df.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  str
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  str
 4   education.num   32561 non-null  int64
 5   marital.status  32561 non-null  str
 6   occupation      32561 non-null  str
 7   relationship    32561 non-null  str
 8   race            32561 non-null  str
 9   sex             32561 non-null  str
 10  capital.gain    32561 non-null  int64
 11  capital.loss    32561 non-null  int64
 12  hours.per.week  32561 non-null  int64
 13  native.country  32561 non-null  str
 14  income          32561 non-null  str
dtypes: int64(6), str(9)
memory usage: 6.2 MB

In [4]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

In [5]:
df.isnull().mean()

age               0.0
workclass         0.0
fnlwgt            0.0
education         0.0
education.num     0.0
marital.status    0.0
occupation        0.0
relationship      0.0
race              0.0
sex               0.0
capital.gain      0.0
capital.loss      0.0
hours.per.week    0.0
native.country    0.0
income            0.0
dtype: float64

In [6]:
df["workclass"].value_counts()

workclass
Private             22696
Self-emp-not-inc     2541
Local-gov            2093
?                    1836
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: count, dtype: int64

In [7]:
df.replace("?" , np.nan , inplace = True)

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,NaN,77053,HS-grad,9,Widowed,NaN,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,NaN,186061,Some-college,10,Widowed,NaN,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32557,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32558,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32559,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32560,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

In [8]:
df["income"].value_counts()

income
<=50K    24720
>50K      7841
Name: count, dtype: int64

In [9]:
# target analysis
df["income"].value_counts(normalize=True)

income
<=50K    0.75919
>50K     0.24081
Name: proportion, dtype: float64

In [10]:
df["income"] =  df["income"].map({"<=50K" : 0 , ">50K" : 1})

In [60]:
df.dropna(axis=0  , inplace  = True)
df.shape

(30162, 15)

In [61]:
x = df.drop("income" , axis = 1)
y  =  df.income

x.shape , y.shape

((30162, 14), (30162,))

In [62]:
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test =  train_test_split(x , y , train_size=0.8 , random_state=42 , stratify=y )

In [63]:
x_train

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country
13322,22,Self-emp-inc,150683,HS-grad,9,Never-married,Machine-op-inspct,Own-child,White,Male,0,0,24,United-States
28882,25,State-gov,262664,Bachelors,13,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States
22,61,Private,29059,HS-grad,9,Divorced,Sales,Unmarried,White,Female,0,2754,25,United-States
8588,44,Federal-gov,44822,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States
26747,50,Self-emp-inc,140516,Bachelors,13,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23895,47,Private,341471,HS-grad,9,Divorced,Priv-house-serv,Not-in-family,White,Female,0,0,4,United-States
24093,19,Private,93518,Some-college,10,Never-married,Sales,Own-child,White,Female,0,0,20,United-States
11386,35,Self-emp-inc,196373,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States
18187,22,Private,173736,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States
13033,31,Private,341672,Bachelors,13,Married-civ-spouse,Adm-clerical,Husband,Asian-Pac-Islander,Male,0,0,60,India

In [64]:
y_train.value_counts(normalize = True)

income
0    0.751088
1    0.248912
Name: proportion, dtype: float64

In [65]:
y_test.value_counts(normalize = True)

income
0    0.751036
1    0.248964
Name: proportion, dtype: float64

In [66]:
x_train.dtypes

age               int64
workclass           str
fnlwgt            int64
education           str
education.num     int64
marital.status      str
occupation          str
relationship        str
race                str
sex                 str
capital.gain      int64
capital.loss      int64
hours.per.week    int64
native.country      str
dtype: object

In [67]:
cat = x_train.select_dtypes("str").columns.tolist()
num = x_train.select_dtypes("number").columns.tolist()

In [68]:
cat  , num

(['workclass',
  'education',
  'marital.status',
  'occupation',
  'relationship',
  'race',
  'sex',
  'native.country'],
 ['age',
  'fnlwgt',
  'education.num',
  'capital.gain',
  'capital.loss',
  'hours.per.week'])

In [69]:
df["education"].nunique()

16

In [70]:
x_train[cat]

,workclass,education,marital.status,occupation,relationship,race,sex,native.country
13322,Self-emp-inc,HS-grad,Never-married,Machine-op-inspct,Own-child,White,Male,United-States
28882,State-gov,Bachelors,Married-civ-spouse,Protective-serv,Husband,White,Male,United-States
22,Private,HS-grad,Divorced,Sales,Unmarried,White,Female,United-States
8588,Federal-gov,Some-college,Married-civ-spouse,Craft-repair,Husband,White,Male,United-States
26747,Self-emp-inc,Bachelors,Married-civ-spouse,Adm-clerical,Husband,White,Male,United-States
...,...,...,...,...,...,...,...,...
23895,Private,HS-grad,Divorced,Priv-house-serv,Not-in-family,White,Female,United-States
24093,Private,Some-college,Never-married,Sales,Own-child,White,Female,United-States
11386,Self-emp-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,United-States
18187,Private,HS-grad,Married-civ-spouse,Craft-repair,Husband,White,Male,United-States
13033,Private,Bachelors,Married-civ-spouse,Adm-clerical,Husband,Asian-Pac-Islander,Male,India

In [71]:
from sklearn.preprocessing import OneHotEncoder , StandardScaler , OrdinalEncoder
from sklearn.compose import ColumnTransformer

In [72]:
ohe =  OneHotEncoder(handle_unknown="ignore")


preprocessor  =  ColumnTransformer(
    transformers= [
    ("num" , StandardScaler()      , num)  , 
    ("cat" , OrdinalEncoder(handle_unknown="use_encoded_value" , unknown_value=-1) , cat)


    ]
)

In [73]:
x_train

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country
13322,22,Self-emp-inc,150683,HS-grad,9,Never-married,Machine-op-inspct,Own-child,White,Male,0,0,24,United-States
28882,25,State-gov,262664,Bachelors,13,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States
22,61,Private,29059,HS-grad,9,Divorced,Sales,Unmarried,White,Female,0,2754,25,United-States
8588,44,Federal-gov,44822,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States
26747,50,Self-emp-inc,140516,Bachelors,13,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23895,47,Private,341471,HS-grad,9,Divorced,Priv-house-serv,Not-in-family,White,Female,0,0,4,United-States
24093,19,Private,93518,Some-college,10,Never-married,Sales,Own-child,White,Female,0,0,20,United-States
11386,35,Self-emp-inc,196373,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States
18187,22,Private,173736,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States
13033,31,Private,341672,Bachelors,13,Married-civ-spouse,Adm-clerical,Husband,Asian-Pac-Islander,Male,0,0,60,India

In [74]:
x_train_proc = preprocessor.fit_transform(x_train)
x_test_proc = preprocessor.transform(x_test)
x_train_proc

array([[-1.25281888, -0.36935707, -0.44436908, ...,  4.        ,
         1.        , 37.        ],
       [-1.02495436,  0.69305168,  1.1280865 , ...,  4.        ,
         1.        , 37.        ],
       [ 1.70941988, -1.52325285, -0.44436908, ...,  4.        ,
         0.        , 37.        ],
       ...,
       [-0.26540596,  0.06412232,  1.1280865 , ...,  4.        ,
         1.        , 37.        ],
       [-1.25281888, -0.150644  , -0.44436908, ...,  4.        ,
         1.        , 37.        ],
       [-0.56922532,  1.44263234,  1.1280865 , ...,  1.        ,
         1.        , 17.        ]], shape=(24129, 14))

In [75]:
x_train

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country
13322,22,Self-emp-inc,150683,HS-grad,9,Never-married,Machine-op-inspct,Own-child,White,Male,0,0,24,United-States
28882,25,State-gov,262664,Bachelors,13,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States
22,61,Private,29059,HS-grad,9,Divorced,Sales,Unmarried,White,Female,0,2754,25,United-States
8588,44,Federal-gov,44822,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States
26747,50,Self-emp-inc,140516,Bachelors,13,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23895,47,Private,341471,HS-grad,9,Divorced,Priv-house-serv,Not-in-family,White,Female,0,0,4,United-States
24093,19,Private,93518,Some-college,10,Never-married,Sales,Own-child,White,Female,0,0,20,United-States
11386,35,Self-emp-inc,196373,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States
18187,22,Private,173736,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States
13033,31,Private,341672,Bachelors,13,Married-civ-spouse,Adm-clerical,Husband,Asian-Pac-Islander,Male,0,0,60,India

In [80]:
from sklearn.linear_model import   LogisticRegression  , LinearRegression

In [ ]:
model  =  LogisticRegression(max_iter=1000 )
# model   = LinearRegression()

model.fit(x_train_proc  , y_train)

LogisticRegression(max_iter=1000000)

In [118]:
preds = model.predict(x_test_proc)
preds

array([1, 0, 1, ..., 0, 0, 0], shape=(6033,))

In [119]:
preds_train = model.predict(x_train_proc)
# preds

In [120]:
accuracy_score(y_train , preds_train)

0.81777114675287

In [121]:
y_test.values[:5]

array([0, 0, 1, 0, 0])

In [122]:
from sklearn.metrics import accuracy_score ,precision_score  , recall_score

In [123]:
accuracy_score(y_test  , preds )

0.8305983756008619

In [127]:
precision_score(y_test , preds)

0.7553191489361702

In [126]:
recall_score(y_test , preds)

0.47270306258322237

In [128]:
import joblib

In [129]:
joblib.dump(model , "model.pkl")

['model.pkl']

In [130]:
mm  = joblib.load("model.pkl")

In [131]:
mm.predict(x_test_proc)

array([1, 0, 1, ..., 0, 0, 0], shape=(6033,))